name: Android CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build
        run: ./gradlew build
